DROP TABLE TOURNAMENTS;
DROP TABLE MATCHES;
DROP TABLE TEAMS;
CREATE TABLE IF NOT EXISTS TOURNAMENTS
(
    ID SERIAL PRIMARY KEY NOT NULL,
    ROUNDS int
    );

CREATE TABLE IF NOT EXISTS MATCHES
(
    ID integer PRIMARY KEY NOT NULL,
    FIRSTTEAMID int NOT NULL,
    SECONDTEAMID int NOT NULL,
    TOURNAMENTID int NOT NULL,
    ROUND int NOT NUll,
    MATCHRESULT varchar(10)
    );

CREATE TABLE IF NOT EXISTS TEAMS
(
    ID integer PRIMARY KEY NOT NULL,
    TEAMNAME varchar(30) NOT NULL,
    COACH varchar(30) NOT NULL,
    CAPTAIN varchar(30) NOT NULL
   );