
CREATE TABLE IF NOT EXISTS addresses (
id INT NOT NULL AUTO_INCREMENT,
address VARCHAR(30) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY (address)
) ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS emails (
id INT NOT NULL AUTO_INCREMENT,
to_addr_id INT NOT NULL,
subject VARCHAR(20) NOT NULL,
text TEXT CHARACTER SET utf8,
sentDate DATETIME NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (to_addr_id) REFERENCES addresses(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;
