CREATE TABLE IF NOT EXISTS TEAMS (
    ID integer PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL,
    CAPTAIN varchar(100) NOT NULL,
    COACH varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MATCHES (
    ID integer PRIMARY KEY NOT NULL,
    ROUND integer NOT NULL,
    TEAM1_ID integer,
    TEAM2_ID integer,
    SCORE varchar(50) NOT NULL,
    FOREIGN KEY(team1_id) REFERENCES TEAMS(ID),
    FOREIGN KEY(team2_id) REFERENCES TEAMS(ID)
);