CREATE TABLE IF NOT EXISTS TOURNAMENT
(
    ID smallint PRIMARY KEY NOT NULL IDENTITY,
    NAME varchar(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS TEAMS
(
    ID integer PRIMARY KEY NOT NULL IDENTITY,
    NAME varchar(100) NOT NULL,
    CAPTAIN varchar(100) NOT NULL,
    COACH varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS GAMES
(
    ID integer PRIMARY KEY NOT NULL IDENTITY,
    FIRST_TEAM integer NOT NULL,
    SECOND_TEAM integer NOT NULL,
    ROUND varchar(100) NOT NULL,
    RESULT varchar(100) NOT NULL,
    TOURNAMENT integer NOT NULL,

);


