INSERT INTO TOURNAMENT (ID, NAME) VALUES (0, 'UEFA Champions League');
INSERT INTO TOURNAMENT (ID, NAME) VALUES (1, 'FIFA World Cup');


INSERT INTO TEAMS (ID, NAME, CAPTAIN, COACH) VALUES (0, 'Manchester United F.C.', 'Cristiano Ronaldo', 'Paul Pogba');
INSERT INTO TEAMS (ID, NAME, CAPTAIN, COACH) VALUES (1, 'Paris Saint-Germain F.C.', 'Lionel Messi','Neymar');
INSERT INTO TEAMS (ID, NAME, CAPTAIN, COACH) VALUES (2, 'Liverpool F.C.', 'Mohamed Salah', 'John Houlding');
INSERT INTO TEAMS (ID, NAME, CAPTAIN, COACH) VALUES (3, 'Chelsea F.C.', 'Romelu Lukaku','Christian Pulisic');

INSERT INTO TEAMS (ID, NAME, CAPTAIN, COACH) VALUES (4, 'FC Barcelona', 'Ansu Fati', 'Joan Laporta');
INSERT INTO TEAMS (ID, NAME, CAPTAIN, COACH) VALUES (5, 'Juventus F.C.', 'Paulo Dybala','Federico Chiesa');
INSERT INTO TEAMS (ID, NAME, CAPTAIN, COACH) VALUES (6, 'A.C. Milan', 'Zlatan Ibrahimovic', 'Stefano Pioli');
INSERT INTO TEAMS (ID, NAME, CAPTAIN, COACH) VALUES (7, 'Manchester City F.C.', 'Jack Grealish','Kevin De Bruyne');

INSERT INTO GAMES (ID, FIRST_TEAM, SECOND_TEAM, ROUND, RESULT, TOURNAMENT) VALUES (0, 0, 1, '1/2', '1:0', 0);
INSERT INTO GAMES (ID, FIRST_TEAM, SECOND_TEAM, ROUND, RESULT, TOURNAMENT) VALUES (1, 2, 3, '1/2', '1:0', 0);
INSERT INTO GAMES (ID, FIRST_TEAM, SECOND_TEAM, ROUND, RESULT, TOURNAMENT) VALUES (2, 0, 2, 'final', '1:0', 0);

INSERT INTO GAMES (ID, FIRST_TEAM, SECOND_TEAM, ROUND, RESULT, TOURNAMENT ) VALUES (3, 4, 5, '1/2', '1:0', 1);
INSERT INTO GAMES (ID, FIRST_TEAM, SECOND_TEAM, ROUND, RESULT, TOURNAMENT ) VALUES (4, 6, 7, '1/2', '1:0', 1);
INSERT INTO GAMES (ID, FIRST_TEAM, SECOND_TEAM, ROUND, RESULT, TOURNAMENT ) VALUES (5, 4, 6, 'final', '1:0', 1);
